version: "3"

services:

  frontend:
    build: ./shop-frontend
    restart: always
    environment:
      - REACT_APP_API_PORT=4322
    ports:
      - "4321:80"
    depends_on:
      - api
    links:
      - "api:backend"


  api:
    build: ./shop-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "4322:4200"

