version: "3"

services:

  frontend:
    build: ./shop-frontend
    restart: always
    ports:
      - "4321:80"
    depends_on:
      - api
    links:
      - "api:backend"


  api:
    build: ./shop-backend
    restart: always
    ports:
      - "4322:4200"
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
